version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: root
    ports:
      - 5432:5432
    volumes:
      - pg_zeera:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_zeera:/data

volumes:
  pg_zeera:
    external: true
  redis_zeera:
    external: true
